/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a48e48e5-5746-47e4-81fb-fb855f789f7d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JpDqPSlW1",
    "aws_user_pools_web_client_id": "5o2rqjg0cqg1etamcd55hbpsi6",
    "oauth": {}
};


export default awsmobile;
